"""Independent Notifications records and durable receiving work.

Revision ID: 1301_notifications
Revises: None
"""

import sqlalchemy as sa
from alembic import op

revision = "1301_notifications"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message_inbox",
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("body", sa.LargeBinary(), nullable=False),
        sa.Column("body_sha256", sa.CHAR(length=64), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.String(length=64), nullable=True),
        sa.CheckConstraint(
            "body_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_message_inbox_body_hash")
        ),
        sa.CheckConstraint(
            "state IN ('PENDING', 'RETRY_WAIT', 'DONE', 'BLOCKED')",
            name=op.f("ck_message_inbox_state"),
        ),
        sa.CheckConstraint(
            "type IN ('shipment.status_changed.v1')", name=op.f("ck_message_inbox_type")
        ),
        sa.CheckConstraint(
            "(lease_token IS NULL) = (lease_until IS NULL)",
            name=op.f("ck_message_inbox_lease_pair"),
        ),
        sa.CheckConstraint(
            "attempts BETWEEN 0 AND 5 AND generation >= 0", name=op.f("ck_message_inbox_attempts")
        ),
        sa.CheckConstraint("octet_length(body) <= 65536", name=op.f("ck_message_inbox_body_limit")),
        sa.PrimaryKeyConstraint("message_id", name=op.f("pk_message_inbox")),
        sa.UniqueConstraint("type", "event_id", name="uq_message_inbox_type_event"),
    )
    op.create_index(
        "ix_message_inbox_pending", "message_inbox", ["state", "next_attempt_at"], unique=False
    )
    op.create_table(
        "message_quarantine",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("fingerprint", sa.CHAR(length=64), nullable=False),
        sa.Column("body", sa.LargeBinary(), nullable=False),
        sa.Column("original_size", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "octet_length(body) <= 65536", name=op.f("ck_message_quarantine_body_limit")
        ),
        sa.CheckConstraint(
            "original_size >= octet_length(body)", name=op.f("ck_message_quarantine_original_size")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_quarantine")),
    )
    op.create_table(
        "message_rearm",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("stage", sa.String(length=16), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("body_sha256", sa.CHAR(length=64), nullable=False),
        sa.Column("previous_attempts", sa.Integer(), nullable=False),
        sa.Column("previous_reason", sa.String(length=64), nullable=True),
        sa.Column("reason", sa.String(length=240), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "body_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_message_rearm_body_hash")
        ),
        sa.CheckConstraint("btrim(reason) <> ''", name=op.f("ck_message_rearm_reason")),
        sa.CheckConstraint("stage = 'inbox'", name=op.f("ck_message_rearm_stage")),
        sa.CheckConstraint(
            "generation > 0 AND previous_attempts BETWEEN 0 AND 5",
            name=op.f("ck_message_rearm_attempts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_rearm")),
        sa.UniqueConstraint(
            "stage", "message_id", "generation", name="uq_message_rearm_generation"
        ),
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("shipment_id", sa.Uuid(), nullable=False),
        sa.Column("tracking_event_id", sa.Uuid(), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("recipient", sa.String(length=254), nullable=False),
        sa.Column("template_key", sa.String(length=80), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("simulated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("origin", sa.String(length=16), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "(origin = 'ASYNC' AND message_id IS NOT NULL) OR "
            "(origin = 'LEGACY' AND message_id IS NULL)",
            name=op.f("ck_notifications_notification_source"),
        ),
        sa.CheckConstraint("btrim(message) <> ''", name=op.f("ck_notifications_message_nonempty")),
        sa.CheckConstraint(
            "btrim(recipient) <> ''", name=op.f("ck_notifications_recipient_nonempty")
        ),
        sa.CheckConstraint(
            "btrim(template_key) <> ''", name=op.f("ck_notifications_template_key_nonempty")
        ),
        sa.CheckConstraint(
            "channel IN ('EMAIL')", name=op.f("ck_notifications_notification_channel")
        ),
        sa.CheckConstraint(
            "origin IN ('ASYNC', 'LEGACY')", name=op.f("ck_notifications_notification_origin")
        ),
        sa.CheckConstraint(
            "status IN ('SIMULATED', 'FAILED')", name=op.f("ck_notifications_notification_status")
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["message_inbox.message_id"],
            name=op.f("fk_notifications_message_id_message_inbox"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
        sa.UniqueConstraint("message_id", name="uq_notifications_message_id"),
        sa.UniqueConstraint("tracking_event_id", name="uq_notifications_tracking_event_id"),
    )
    op.create_index(
        "ix_notifications_status_created_at",
        "notifications",
        ["status", sa.literal_column("created_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notifications")
    op.drop_table("message_rearm")
    op.drop_table("message_quarantine")
    op.drop_table("message_inbox")
    # ### end Alembic commands ###
