"""Durable Tracking transport tables owned by core."""

import sqlalchemy as sa
from alembic import op

revision = "1201_core"
down_revision = "1101_core"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message_outbox",
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("body", sa.LargeBinary(), nullable=False),
        sa.Column("body_sha256", sa.CHAR(length=64), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.String(length=64), nullable=True),
        sa.CheckConstraint(
            "body_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_message_outbox_body_hash")
        ),
        sa.CheckConstraint(
            "state IN ('PENDING', 'LEASED', 'SENT', 'BLOCKED')",
            name=op.f("ck_message_outbox_state"),
        ),
        sa.CheckConstraint(
            "type IN ('tracking.apply.v1', 'tracking.result.v1')",
            name=op.f("ck_message_outbox_type"),
        ),
        sa.CheckConstraint(
            "(lease_token IS NULL) = (lease_until IS NULL)",
            name=op.f("ck_message_outbox_lease_pair"),
        ),
        sa.CheckConstraint(
            "attempts BETWEEN 0 AND 5 AND generation >= 0", name=op.f("ck_message_outbox_attempts")
        ),
        sa.CheckConstraint(
            "octet_length(body) <= 65536", name=op.f("ck_message_outbox_body_limit")
        ),
        sa.PrimaryKeyConstraint("message_id", name=op.f("pk_message_outbox")),
        sa.UniqueConstraint("type", "event_id", name="uq_message_outbox_type_event"),
    )
    op.create_index(
        "ix_message_outbox_pending", "message_outbox", ["state", "next_attempt_at"], unique=False
    )
    op.create_table(
        "message_inbox",
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=False),
        sa.Column("body", sa.LargeBinary(), nullable=False),
        sa.Column("body_sha256", sa.CHAR(length=64), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.String(length=64), nullable=True),
        sa.CheckConstraint(
            "body_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_message_inbox_body_hash")
        ),
        sa.CheckConstraint(
            "state IN ('PENDING', 'RETRY_WAIT', 'DONE', 'BLOCKED')",
            name=op.f("ck_message_inbox_state"),
        ),
        sa.CheckConstraint(
            "type IN ('tracking.apply.v1', 'tracking.result.v1')",
            name=op.f("ck_message_inbox_type"),
        ),
        sa.CheckConstraint(
            "(lease_token IS NULL) = (lease_until IS NULL)",
            name=op.f("ck_message_inbox_lease_pair"),
        ),
        sa.CheckConstraint(
            "attempts BETWEEN 0 AND 5 AND generation >= 0", name=op.f("ck_message_inbox_attempts")
        ),
        sa.CheckConstraint("octet_length(body) <= 65536", name=op.f("ck_message_inbox_body_limit")),
        sa.PrimaryKeyConstraint("message_id", name=op.f("pk_message_inbox")),
        sa.UniqueConstraint("type", "event_id", name="uq_message_inbox_type_event"),
    )
    op.create_index(
        "ix_message_inbox_pending", "message_inbox", ["state", "next_attempt_at"], unique=False
    )
    op.create_table(
        "message_quarantine",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("fingerprint", sa.CHAR(length=64), nullable=False),
        sa.Column("body", sa.LargeBinary(), nullable=False),
        sa.Column("original_size", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "octet_length(body) <= 65536", name=op.f("ck_message_quarantine_body_limit")
        ),
        sa.CheckConstraint(
            "original_size >= octet_length(body)", name=op.f("ck_message_quarantine_original_size")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_quarantine")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("message_quarantine")
    op.drop_table("message_inbox")
    op.drop_table("message_outbox")
    # ### end Alembic commands ###
